name: pytest

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
    
    - name: Install Package
      run: pip3 intall -r BE\ -\ Berat/requirements.txt
      shell: bash

    - name: Run pytest
      run: |
        cd  BE\ -\ Berat/requirements.txt
        python3 -m pytest -v
      shell: bash
